name: webapp
description: This is a package for fast, easy, and powerful web application development using the Dart language.
version: 1.0.18
homepage: https://uproid.com/webapp
repository: https://github.com/uproid/webapp.git
issue_tracker: https://github.com/uproid/webapp/issues

platforms:
  web:
  linux:
  windows:
  macos:
  
sdk:
  dart:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dotenv: ^4.2.0
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.3
  encrypt: ^5.0.3
  crypto: ^3.0.3
  logger: ^2.3.0
  mailer: ^6.1.1
  jinja: ^0.6.0 
  intl: ^0.19.0
  mime: ^1.0.5
  cron: ^0.6.1
  base32: ^2.1.3

