name: dartweb
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://uproid.com/dartweb

publish_to: "https://pub.dev"
repository: https://github.com/uproid/dartweb.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dotenv: ^4.2.0
  json_annotation: ^4.9.0
  mongo_dart: ^0.10.3
  encrypt: ^5.0.3
  crypto: ^3.0.3
  logger: ^2.3.0
  mailer: ^6.1.1
  jinja: ^0.6.0 
  intl: ^0.19.0
  mime: ^1.0.5
  cron: ^0.6.1
  base32: ^2.1.3

